// <auto-generated />
using System;
using EShop.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20230325073542_AddDescriptionFieldToBookModel")]
    partial class AddDescriptionFieldToBookModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Domain.Entities.Access.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Access.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Account.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailActivationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<long?>("PublisherId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Shabak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "الیف شافاک",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9245),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9246),
                            Price = 95000,
                            PublisherId = 1L,
                            Release_Date = new DateTime(2015, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789643119195",
                            Title = "عاشقانه ملت عشق"
                        },
                        new
                        {
                            Id = 2L,
                            Author = "فردریک بکمن",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9249),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9250),
                            Price = 95000,
                            PublisherId = 2L,
                            Release_Date = new DateTime(2016, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786007141779",
                            Title = "مردی به نام اوه"
                        },
                        new
                        {
                            Id = 3L,
                            Author = "اروین یالوم",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9252),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9253),
                            Price = 65000,
                            PublisherId = 3L,
                            Release_Date = new DateTime(2020, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786001192029",
                            Title = "وقتی نیچه گریست"
                        },
                        new
                        {
                            Id = 4L,
                            Author = "استیو تولتز",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9255),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9256),
                            Price = 160000,
                            PublisherId = 4L,
                            Release_Date = new DateTime(2016, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786002295002",
                            Title = "جزء از کل"
                        },
                        new
                        {
                            Id = 5L,
                            Author = "ژان تولی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9258),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9259),
                            Price = 38000,
                            PublisherId = 4L,
                            Release_Date = new DateTime(2018, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786002298812",
                            Title = "مغازه خودکشی"
                        },
                        new
                        {
                            Id = 6L,
                            Author = "جورج اورول‌",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9261),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9262),
                            Price = 5000,
                            PublisherId = 15L,
                            Release_Date = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "964604799",
                            Title = "مزرعۀ حیوانات"
                        },
                        new
                        {
                            Id = 7L,
                            Author = "شارون گاسکین",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9264),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9265),
                            Price = 55000,
                            PublisherId = 16L,
                            Release_Date = new DateTime(2020, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004613644",
                            Title = "زمان فراموشی"
                        },
                        new
                        {
                            Id = 8L,
                            Author = "پم مونیوس رایان",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9289),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9290),
                            Price = 49000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004624763",
                            Title = "از سرزمین‌های انگور"
                        },
                        new
                        {
                            Id = 9L,
                            Author = "دبورا ھاپکینسن",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9291),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9292),
                            Price = 49000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004625104",
                            Title = "گوشه‌ی دنج کلاس"
                        },
                        new
                        {
                            Id = 10L,
                            Author = "صادق هدایت",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9294),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9295),
                            Price = 8500,
                            PublisherId = 17L,
                            Release_Date = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004516464",
                            Title = "سه قطره خون"
                        },
                        new
                        {
                            Id = 11L,
                            Author = "ام. تی. ادواردسن",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9297),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9298),
                            Price = 70000,
                            PublisherId = 16L,
                            Release_Date = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004613637",
                            Title = "یک خانوادۀ تقریباً معمولی"
                        },
                        new
                        {
                            Id = 12L,
                            Author = "ژاک شابان",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9300),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9301),
                            Price = 12000,
                            PublisherId = 18L,
                            Release_Date = new DateTime(2015, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786001760112",
                            Title = "شب ترمیدور"
                        },
                        new
                        {
                            Id = 13L,
                            Author = "الیف شافاک",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9302),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9303),
                            Price = 69000,
                            PublisherId = 19L,
                            Release_Date = new DateTime(2017, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786003672765",
                            Title = "اسکندر"
                        },
                        new
                        {
                            Id = 14L,
                            Author = "فیودور داستایوفسکی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9305),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9306),
                            Price = 16000,
                            PublisherId = 18L,
                            Release_Date = new DateTime(2022, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789642575398",
                            Title = "رویای عمو جان"
                        },
                        new
                        {
                            Id = 15L,
                            Author = "جینین ساندرز ، کریگ اسمیت",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9308),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9309),
                            Price = 49000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004623377",
                            Title = "بعضی از رازها را نباید نگه‌داشت"
                        },
                        new
                        {
                            Id = 16L,
                            Author = "رابین شارما",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9311),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9312),
                            Price = 158000,
                            PublisherId = 20L,
                            Release_Date = new DateTime(2021, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786226242226",
                            Title = "باشگاه پنج صبحی‌‌ها"
                        },
                        new
                        {
                            Id = 17L,
                            Author = "استیون هاوکینگ",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9314),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9315),
                            Price = 8000,
                            PublisherId = 21L,
                            Release_Date = new DateTime(2022, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786009896196",
                            Title = "جهان در پوست گردو"
                        },
                        new
                        {
                            Id = 18L,
                            Author = "ليليان گلاس",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9316),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9317),
                            Price = 8000,
                            PublisherId = 21L,
                            Release_Date = new DateTime(2022, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786009896356",
                            Title = "آدم های سمی"
                        },
                        new
                        {
                            Id = 19L,
                            Author = "دارن هاردی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9319),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9320),
                            Price = 8000,
                            PublisherId = 21L,
                            Release_Date = new DateTime(2020, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786009896141",
                            Title = "اثر مرکب"
                        },
                        new
                        {
                            Id = 20L,
                            Author = "شلی استايل",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9323),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9324),
                            Price = 15000,
                            PublisherId = 22L,
                            Release_Date = new DateTime(2016, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789643288464",
                            Title = "بعد از طلاق"
                        },
                        new
                        {
                            Id = 21L,
                            Author = "آرون تی‌بک",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9326),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9327),
                            Price = 35000,
                            PublisherId = 23L,
                            Release_Date = new DateTime(2018, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789647390569",
                            Title = "عشق هرگز کافی نیست"
                        },
                        new
                        {
                            Id = 22L,
                            Author = "چارلز هانل",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9329),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9330),
                            Price = 25000,
                            PublisherId = 23L,
                            Release_Date = new DateTime(2011, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786001180248",
                            Title = "شاه کلید"
                        },
                        new
                        {
                            Id = 23L,
                            Author = "استیون میچل ، بایرون کیتی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9331),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9332),
                            Price = 95000,
                            PublisherId = 24L,
                            Release_Date = new DateTime(2021, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786226683661",
                            Title = "هزار و یک‌دلیل برای شادبودن"
                        },
                        new
                        {
                            Id = 24L,
                            Author = "نسرین دانائی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9334),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9335),
                            Price = 25000,
                            PublisherId = 13L,
                            Release_Date = new DateTime(2020, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789643729691",
                            Title = "مدیریت هیجان"
                        },
                        new
                        {
                            Id = 25L,
                            Author = "ریچل هالیس",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9337),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9338),
                            Price = 64000,
                            PublisherId = 20L,
                            Release_Date = new DateTime(2020, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786226242233",
                            Title = "صورتت را بشور دختر"
                        },
                        new
                        {
                            Id = 26L,
                            Author = "جیم ران",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9340),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9341),
                            Price = 20000,
                            PublisherId = 23L,
                            Release_Date = new DateTime(2018, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786001182136",
                            Title = "فلسفۀ زندگی موفق"
                        },
                        new
                        {
                            Id = 27L,
                            Author = "روندا برن",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9342),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9343),
                            Price = 45000,
                            PublisherId = 23L,
                            Release_Date = new DateTime(2015, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786001181528",
                            Title = "قهرمان"
                        },
                        new
                        {
                            Id = 28L,
                            Author = "سهراب سپهری",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9345),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9346),
                            Price = 10000,
                            PublisherId = 13L,
                            Release_Date = new DateTime(2004, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "964372056x",
                            Title = "عاشق همیشه تنهاست"
                        },
                        new
                        {
                            Id = 29L,
                            Author = "علی باباچاهی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9349),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9350),
                            Price = 68000,
                            PublisherId = 10L,
                            Release_Date = new DateTime(2020, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789647230018",
                            Title = "این بانگ دلاویز"
                        },
                        new
                        {
                            Id = 30L,
                            Author = "سیّد رضا محمدی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9352),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9353),
                            Price = 9000,
                            PublisherId = 16L,
                            Release_Date = new DateTime(2018, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004610650",
                            Title = "سفرنامۀ باد"
                        },
                        new
                        {
                            Id = 31L,
                            Author = "مصطفی سپهری‌نیا",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9354),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9355),
                            Price = 4500,
                            PublisherId = 17L,
                            Release_Date = new DateTime(2020, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004514552",
                            Title = "خواب‌های مرگ‌آلود"
                        },
                        new
                        {
                            Id = 32L,
                            Author = "مسیحا برزگر",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9357),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9358),
                            Price = 20000,
                            PublisherId = 23L,
                            Release_Date = new DateTime(2022, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786001180613",
                            Title = "ما به عشق محتاجیم!"
                        },
                        new
                        {
                            Id = 33L,
                            Author = "کامیار عابدی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9360),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9361),
                            Price = 78000,
                            PublisherId = 10L,
                            Release_Date = new DateTime(2021, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789646404106",
                            Title = "در زلالِ شعر"
                        },
                        new
                        {
                            Id = 34L,
                            Author = "پدرام حکیم‌زاده",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9363),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9364),
                            Price = 6000,
                            PublisherId = 25L,
                            Release_Date = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786007811863",
                            Title = "شب‌های حافظ"
                        },
                        new
                        {
                            Id = 35L,
                            Author = "پدرام حکیم‌زاده",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9365),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9366),
                            Price = 14000,
                            PublisherId = 25L,
                            Release_Date = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786227395969",
                            Title = "رعشه شاعران"
                        },
                        new
                        {
                            Id = 36L,
                            Author = "پدرام حکیم‌زاده",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9368),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9369),
                            Price = 12000,
                            PublisherId = 25L,
                            Release_Date = new DateTime(2018, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786007811757",
                            Title = "افسونگر چرخ کبود"
                        },
                        new
                        {
                            Id = 37L,
                            Author = "پدرام حکیم‌زاده ، مصلح‌بن عبدالله سعدی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9371),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9372),
                            Price = 6000,
                            PublisherId = 25L,
                            Release_Date = new DateTime(2018, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786007811764",
                            Title = "صدای امواج"
                        },
                        new
                        {
                            Id = 38L,
                            Author = "مک بارنت",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9375),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9375),
                            Price = 49000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2018, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786008347170",
                            Title = "آن پایین چه خبر است؟"
                        },
                        new
                        {
                            Id = 39L,
                            Author = "جاناتان لاندِن",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9377),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9378),
                            Price = 49000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2019, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004622585",
                            Title = "چتری برای دو نفر"
                        },
                        new
                        {
                            Id = 40L,
                            Author = "لیزا مَنچاو",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9380),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9381),
                            Price = 29000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2018, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004621144",
                            Title = "ورود فیل‌ها ممنوع!"
                        },
                        new
                        {
                            Id = 41L,
                            Author = "نیک براملی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9383),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9384),
                            Price = 24000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004622523",
                            Title = "با احتیاط باز کنید. خطر گاز گرفتگی!"
                        },
                        new
                        {
                            Id = 42L,
                            Author = "مورین رایت",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9385),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9386),
                            Price = 49000,
                            PublisherId = 14L,
                            Release_Date = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004623032",
                            Title = "آدم برفی سردشه"
                        },
                        new
                        {
                            Id = 43L,
                            Author = "استیون هاوکینگ",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9388),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9389),
                            Price = 8000,
                            PublisherId = 26L,
                            Release_Date = new DateTime(2022, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786008866398",
                            Title = "تاریخچه مختصر زمان"
                        },
                        new
                        {
                            Id = 44L,
                            Author = "ماری رابرت",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9391),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9392),
                            Price = 20000,
                            PublisherId = 16L,
                            Release_Date = new DateTime(2021, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004614139",
                            Title = "بر فراز با فیلسوفان"
                        },
                        new
                        {
                            Id = 45L,
                            Author = "رضا داوری اردکانی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9394),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9395),
                            Price = 25000,
                            PublisherId = 13L,
                            Release_Date = new DateTime(2013, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9789643726195",
                            Title = "اندیشۀ پست مدرن"
                        },
                        new
                        {
                            Id = 46L,
                            Author = "الکساندر نهاماس",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9396),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9397),
                            Price = 35000,
                            PublisherId = 1L,
                            Release_Date = new DateTime(2022, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786220403845",
                            Title = "جایگاه زیبایی در عالم هنر"
                        },
                        new
                        {
                            Id = 47L,
                            Author = "دانیل ام. کلاین",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9400),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9401),
                            Price = 20000,
                            PublisherId = 16L,
                            Release_Date = new DateTime(2021, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004613880",
                            Title = "سفر با اپیکور"
                        },
                        new
                        {
                            Id = 48L,
                            Author = "فريدريش نيچه",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9403),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9404),
                            Price = 95000,
                            PublisherId = 18L,
                            Release_Date = new DateTime(2017, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9645620600",
                            Title = "چنین گفت زرتشت"
                        },
                        new
                        {
                            Id = 49L,
                            Author = "دُن تامپسون",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9405),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9406),
                            Price = 98000,
                            PublisherId = 27L,
                            Release_Date = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786226401203",
                            Title = "کوسهٔ شکم‌پر ۱۲ ‌میلیون دلاری"
                        },
                        new
                        {
                            Id = 50L,
                            Author = "بیل براودر",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9408),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9409),
                            Price = 55000,
                            PublisherId = 16L,
                            Release_Date = new DateTime(2019, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786004611367",
                            Title = "اعلان قرمز"
                        },
                        new
                        {
                            Id = 51L,
                            Author = "حسین سیلسپور",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9411),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9412),
                            Price = 35000,
                            PublisherId = 17L,
                            Release_Date = new DateTime(2017, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786008095866",
                            Title = "آشنایی با بازارهای بورس انرژی"
                        },
                        new
                        {
                            Id = 52L,
                            Author = "آرویند ساتهی",
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9414),
                            Description = "Description",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9415),
                            Price = 52000,
                            PublisherId = 28L,
                            Release_Date = new DateTime(2020, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Shabak = "9786227393170",
                            Title = "تجزیه و تحلیل کلان داده‌ها"
                        });
                });

            modelBuilder.Entity("EShop.Domain.Entities.BookCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BookId = 1L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            BookId = 2L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            BookId = 3L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            BookId = 4L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            BookId = 5L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            BookId = 6L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            BookId = 7L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            BookId = 8L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            BookId = 9L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            BookId = 10L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            BookId = 11L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            BookId = 12L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            BookId = 13L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            BookId = 14L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            BookId = 15L,
                            CategoryId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            BookId = 16L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            BookId = 17L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            BookId = 18L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 19L,
                            BookId = 19L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            BookId = 20L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 21L,
                            BookId = 21L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            BookId = 22L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 23L,
                            BookId = 23L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            BookId = 24L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 25L,
                            BookId = 25L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            BookId = 26L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 27L,
                            BookId = 27L,
                            CategoryId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            BookId = 28L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            BookId = 29L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 30L,
                            BookId = 30L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 31L,
                            BookId = 31L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            BookId = 32L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 33L,
                            BookId = 33L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 34L,
                            BookId = 34L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 35L,
                            BookId = 35L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 36L,
                            BookId = 36L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 37L,
                            BookId = 37L,
                            CategoryId = 3L
                        },
                        new
                        {
                            Id = 38L,
                            BookId = 38L,
                            CategoryId = 4L
                        },
                        new
                        {
                            Id = 39L,
                            BookId = 39L,
                            CategoryId = 4L
                        },
                        new
                        {
                            Id = 40L,
                            BookId = 40L,
                            CategoryId = 4L
                        },
                        new
                        {
                            Id = 41L,
                            BookId = 41L,
                            CategoryId = 4L
                        },
                        new
                        {
                            Id = 42L,
                            BookId = 42L,
                            CategoryId = 4L
                        },
                        new
                        {
                            Id = 43L,
                            BookId = 43L,
                            CategoryId = 5L
                        },
                        new
                        {
                            Id = 44L,
                            BookId = 44L,
                            CategoryId = 5L
                        },
                        new
                        {
                            Id = 45L,
                            BookId = 45L,
                            CategoryId = 5L
                        },
                        new
                        {
                            Id = 46L,
                            BookId = 46L,
                            CategoryId = 5L
                        },
                        new
                        {
                            Id = 47L,
                            BookId = 47L,
                            CategoryId = 5L
                        },
                        new
                        {
                            Id = 48L,
                            BookId = 48L,
                            CategoryId = 6L
                        },
                        new
                        {
                            Id = 49L,
                            BookId = 49L,
                            CategoryId = 6L
                        },
                        new
                        {
                            Id = 50L,
                            BookId = 50L,
                            CategoryId = 6L
                        },
                        new
                        {
                            Id = 51L,
                            BookId = 51L,
                            CategoryId = 6L
                        },
                        new
                        {
                            Id = 52L,
                            BookId = 52L,
                            CategoryId = 6L
                        });
                });

            modelBuilder.Entity("EShop.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8204),
                            Description = "داستان‌ها در ادبیات جهان سابقه دور و درازی دارند. این روایت‌ها از زمانی که قصه‌ها سینه به سینه منتقل می‌شدند وجود دارند تا ادبیات معاصر امروز. در هیچ دوره‌ای انسان‌ها بی نیاز از داستان‌ها نیستند. زیرا شیرینی بی‌نظیر و تکرار نشدنی در این وجود دارد که در خیال دیگران غرق شویم و تجربیات ناب لحظه‌های دیگران را مال خود بدانیم.\r\n                داستان محصول ذهن خلاق فردی به نام نویسنده است که شخصیت‌های داستانش را ساخته و پرداخته و به زبان ادبی روایت می‌کند.یک داستان خوب می‌تواند مسیر زندگی شما را تغییر دهد؛ زیرا آموزه های آن در زندگی واقعی کاربرد فراوانی دارد.کتاب به انسان آگاهی می دهد و از تکرار خطاها و کج روی ها پیش گیری می کند.با مطالعه کتب داستانی متنوع می توانیم از حقوق فردی و اجتماعی خود آگاه شویم و از آن دفاع کنیم.\r\n                هم چنین کتاب‌خوانی به کتاب‌خوان فرصت می‌دهد تا بدونِ پرداخت هزینه مالی و جانی‌ که نویسنده یا شخصیت‌های کتاب پرداخت کرده‌اند، تجربه آن‌ها را مال خود کند.این محکم‌ترین دلیل برای کتاب‌خوانی‌ست.جالب است بدانید که با مطالعه مشهورترین رمان های دنیا از سبک زندگی انسان ها در سراسر دنیا آشنا می شویم و می توانیم نقاط مثبت هر یک را در روزمره خود به کار بندیم.",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8226),
                            Name = "داستان و رمان"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8229),
                            Description = "دانش روانشناسی، دانشی است که از نیمه‌ی دوم قرن هفدهم ظهور کرده و شاخه‌های متنوعی دارد. افرادی مانند ژان پیاژه، زیگموند فروید، کارال راجرز و گوستاو یونگ عمرشان را صرف کرده‌اند تا مفاهیم این دانش را تکمیل کنند و از آن برای کمک به بشر در مسیر یک زندگی بهتر بهره ببرند.\r\nدر دنیای امروز که زندگی بسیار پرمشغله‌تر از گذشته شده و روابط پیچیده‌تر شده‌اند همه‌ی افراد به این دانش نیاز دارند. نیاز به خودشناسی در دنیای ما که رسانه‌های مختلف انواع محتوا را به خوردمان می‌دهند و معیارهای متعددی را برای خوشبختی و موفقیت معرفی می‌کنند بسیار بیشتر از گذشته است. امروزه برای یک ازدواج موفق درک درست از شخصیت خودمان و طرف مقابل ضروری است و برای داشتن یک خانواده‌ی سالم نیاز داریم اصول تربیتی را بهتر فرا بگیریم. استفاده از روانشناس بالینی بسیار مفید است اما ممکن است همه به چنین شرایط دسترسی نداشته باشند. جای نگرانی نیست، این روزها دیگر کتاب‌های روانشناسی فقط به کتاب‌های دانشگاهی که مخصوص دانشجویان و متخصصان هستند محدود نمی‌شوند و انواع کتاب فیزیکی و صوتی برای گروه‌های مختلف نوشته‌شده‌اند و به‌ راحتی می‌توانید متناسب با نیازتان یک گزینه‌ی خوب را انتخاب کنید.",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8230),
                            Name = "روانشناسی"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8231),
                            Description = "شعر کلامی تاثیر گذار و سخنی خیال انگیز است که موزون سروده می شود. از زمانی که انسان با مفهوم شعر آشنا شده است همواره آن را آهنگین یافته و مسحور و مفتون آن گشته است.  شاعر نقاش زبردستی است که خوبی ها و بدی ها را به زیبایی در قالب کلمات موزون به تصویر می کشد و با سرودن اشعار لطیف و بدیع توجه همگان را به شعر معطوف می دارد.\r\nدر این میان همواره شعر های عاشقانه و احساسی در طول تاریخ مورد توجه بسیار بوده اند و داستان ها و حکایت های عاشقانه بسیاری به صورت نظم در ادبیات کهن ایران برجای مانده است که در میان آن ها می توان به کتب شعر عاشقانه خسرو و شیرین، لیلی و مجنون و شیرین و فرهاد اشاره کرد.",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8232),
                            Name = "شعر"
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8234),
                            Description = "اهمیت آموزش کودکان و پرورش ذهن آن‌ها برای درک جهانی که در آن زندگی می‌کنند بر کسی پوشیده نیست. کودکان به‌واسطه‌ی کتاب‌ها و دیگر انواع محتوا با پدیده‌های گوناگون آشنا می‌شوند و باعث درک بهتر آنها از پیرامون خود می‌شود تا بتوانند در موقعیت‌های مختلف واکنش مناسبی از خود نشان دهند. کودکان قشری هستند که معمولاً خودشان محتوا را انتخاب نمی‌کنند و نقش خانواده و مربی در معرفی و تهیه آن بسیار زیاد است. برای همین کسب آگاهی و انتخاب محتوای مناسب برای کودکان توسط والدین و خانواده بسیار حائز اهمیت است. کودکان با مطالعه‌ی کتاب‌های علمی می‌توانند پاسخ سوالات خود را پیدا کنند و یا کنجکاو شوند. همچنین کتاب‌های داستان و رمان می‌تواند به آن‌ها کمک کند تا با شخصیت‌های بیشتری آشنا شوند و تجربیات بیشتری کسب کنند و از همه مهم‌تر قوه‌ی تخیل کودکان نیز رشد پیدا کند. یکی از مواردی که باید در خرید کتاب کودک به آن توجه کنیم رده‌ی سنی است.",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8235),
                            Name = "کودک"
                        },
                        new
                        {
                            Id = 5L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8236),
                            Description = "اگر بخواهیم از تعریف کلمه‌ی فلسفه شروع کنیم این کلمه از کلمه‌ی یونانی فیلوسوفیا گرفته شده است و طبق تعریف ویکی پدیا به‌معنای مطالعه پرسش‌های بنیادین عالم است. تاریخ فلسفه تاریخ پر فراز و نشیبی است که از زمان سقراط اولین فیلسوف بزرگ یونان آغاز شده و با افرادی مانند فردریش نیچه، برتراند راسل و ویل دورانت تا امروز ادامه داشته و گسترده شده است. امروز اگر بخواهیم از فلسفه حرف بزنیم باید بدانیم منظورمان فلسفه‌ی غرب است که در یونان ریشه دارد یا می‌خواهیم از فلسفه‌ی شرق حرف بزنیم؟ فلسفه دیگر مانند گذشته محدود نیست و آثار فلسفی هم موضوعات زیادی از فلسفه اخلاق و فلسفه سیاسی تا فلسفه اسلامی و ... را پوشش می‌دهند. گروهی از فلاسفه معتقدند فلسفه تنها متعلق به فیلسوفان است و در زندگی مردم عادی نقشی ندارد اما گروهی هم تلاش کرده‌اند با معرفی کتاب‌هایی مانند رمان‌های فلسفی یا کتاب‌های فلسفی روانشناسی آن را با زندگی روزمره بیامیزند و همین باعث تنوع در آثار فلسفی شده است. ",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8237),
                            Name = "فلسفه"
                        },
                        new
                        {
                            Id = 6L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8238),
                            Description = "اقتصاد در بطن زندگی انسان ریشه دوانده و زندگی روزمره را به شدت تحت تاثیر قرار داده است. ما بدون آنکه به علم اقتصاد و پیچیدگی‌های آن بیاندیشیم، تصمیم‌هایی می‌گیریم که اقتصاد آن را اداره می‌کند. مقایسه‌ی تورهای مسافرتی، خرید اشتراک اینترنت، تعویض ماشین همه و همه به محاسبات اقتصادی و نوع نگاه ما به آن بستگی دارد. علم اقتصاد به زبان ساده به این شکل تعریف می‌شود: یک نظام اقتصادی مربوط به یک منطقه سیاسی یا جغرافیایی خاص است و تولید، توزیع و مصرف کالا و خدمات را دربرمی‌گیرد. در اقتصاد 4 عامل نقش کلیدی ایفا می‌کند: منابع انسانی، منابع مالی، زمین و کسب و کار",
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8239),
                            Name = "اقتصاد"
                        });
                });

            modelBuilder.Entity("EShop.Domain.Entities.Publisher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Establishment_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8892),
                            Description = "فروشگاه انتشارات ققنوس در بهمن‌ماه سال ١٣٥٦ آغاز به کار کرد، اما این آغازِ کار نبود: امیر حسین‌زادگان، مؤسس انتشارات، کارش را در این حوزه از سال ١٣٥٠، در یکی از محلات جنوب‌غربی تهران، مهرآباد جنوبی، و با راه‌اندازی کتابفروشی «امیر»، شروع کرد.",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8895),
                            Name = "گروه انتشاراتی ققنوس"
                        },
                        new
                        {
                            Id = 2L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8897),
                            Description = "ندارد",
                            Establishment_Date = new DateTime(2012, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8898),
                            Name = "نشر نون"
                        },
                        new
                        {
                            Id = 3L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8900),
                            Description = "نشر قطره یک مؤسسه انتشاراتی چاپ و نشر کتاب در ایران است که از سال ۱۳۶۷ آغاز به فعالیت نموده‌است. عناوین کتاب‌های نشر شده توسط این انتشاراتی شامل حوزه‌های مختلفی از جمله ادبیات داستانی داخلی و خارجی،[۱] نمایش‌نامه، داستان کوتاه، کتب آموزشی و غیره می‌گردد.",
                            Establishment_Date = new DateTime(1988, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8901),
                            Name = "نشر قطره"
                        },
                        new
                        {
                            Id = 4L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8902),
                            Description = "نشر چشمه مؤسسات انتشاراتی در ایران که عمده فعالیتش در زمینه ادبیات است.[۱]\r\n                    انتشارات چشمه فعالیت خود را برای انتشار کتاب از سال ۱۳۶۴ شروع کرد.[۲] مدیر این انتشارات سیّد حسن کیائیان موسوی است. این انتشارات در خرداد ۱۳۹۱ از سوی وزارت ارشاد لغو مجوز شد.[۳] و در زمان دولت یازدهم فعالیتش را از سر گرفت. انتشارات چشمه از زمان تأسیس در حوزه‌های مختلف هنر و ادبیات مانند داستان، شعر، نمایشنامه، فیلمنامه، سینما، تحقیقات ادبی، متون کهن، فلسفه، علوم اجتماعی، اسطوره و تاریخ فعالیت کرده‌است.",
                            Establishment_Date = new DateTime(1985, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8904),
                            Name = "نشر چشمه"
                        },
                        new
                        {
                            Id = 5L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8906),
                            Description = "انتشارات نقش و نگار در سال 1373 توسط ابراهیم شهلایی مقدم تأسیس شد و تا به حال بیش از 50 عنوان کتاب در موضوعات عمومی منتشر کرده است.",
                            Establishment_Date = new DateTime(1994, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8907),
                            Name = "انتشارات نقش و نگار"
                        },
                        new
                        {
                            Id = 6L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8945),
                            Description = "",
                            Establishment_Date = new DateTime(2013, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8947),
                            Name = "نشر شمشاد"
                        },
                        new
                        {
                            Id = 7L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8949),
                            Description = "",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8950),
                            Name = "انتشارات نگاه نوین"
                        },
                        new
                        {
                            Id = 8L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8952),
                            Description = "انتشارات درسا از سال 1372 آغاز به کار کرد؛ اما شروع فعالیت فرهنگی این مجموعه به چند سال پیش از آن باز می‌گردد: مرحوم صمد رحیمیان، مؤسس و صاحب‌ امتیاز شرکت نشر و پخش ویس و انتشارات رسام، از سال 1364 فعالیت خود را با تولید کتاب‌هایی در حوزه‌ی علوم سیاسی، ادبیات داستانی، روان‌ شناسی و روان‌ شناسی نوین، در محل کنونی انتشارات درسا آغاز کرد.  در سال 1369 ایشان بنا به دلایلی ناگزیر شد شرکت نشر و پخش ویس را منحل کند. در همین سال به‌ اتفاق همسر و فرزندش (کیوان رحیمیان) نشر درسا را پایه‌گذاری کرد و در پی اخذ پروانه‌ی نشر جدید به نام همسرش در سال 1372، پس از پنج سال نشر لیوسا نیز با مدیریت و صاحب‌امتیازی کیوان رحیمیان وارد فعالیت رسمی در صنعت نشر ایران شد.",
                            Establishment_Date = new DateTime(1985, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8953),
                            Name = "انتشارات درسا"
                        },
                        new
                        {
                            Id = 9L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8954),
                            Description = "",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8955),
                            Name = "نشر راویس"
                        },
                        new
                        {
                            Id = 10L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8957),
                            Description = "نشر ثالث یک شرکت فعال در زمینه چاپ و نشر کتاب می‌باشد که از سال ۱۳۷۵ فعالیت خود را آغاز کرده‌است. این انتشاراتی آثار متعددی را عمدتاً در حوزه‌های علوم انسانی (ادبیات، دین، تاریخ، فلسفه، علوم اجتماعی، روان‌شناسی و هنر) منتشر کرده‌است.[۱][۲] از میان کتاب‌هایی که نشر ثالث منتشر کرده می‌توان به دون کیشوت اثر سروانتس با ترجمه‌ی محمد قاضی ، ریشه‌های توتالیتاریسم اثر هانا آرنت با ترجمه محسن ثلاثی و در حوزه رمان کتابخانه نیمه شب اثر مت هیگ با ترجمه امین حسینیون اشاره کرد.",
                            Establishment_Date = new DateTime(1996, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8957),
                            Name = "نشر ثالث"
                        },
                        new
                        {
                            Id = 11L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8959),
                            Description = "این انتشارات در آستانه فعالیت خود همواره این مهم را مدنظر داشته‌است که نه برای نبرد و رقابت بلکه برای پوشش‌دادن به خلأ موجود در دنیای فرهنگ و هنر پا به عرصه نشر می‌نهد. کمبودی که شاید در حال حاضر وجود آن به طور ملموس قابل درک نباشد؛ اما بدون شک در آینده خود را بیش از پیش نمایان و آشکار می‌سازد.",
                            Establishment_Date = new DateTime(2018, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8960),
                            Name = "نشر بید"
                        },
                        new
                        {
                            Id = 12L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8961),
                            Description = "انتشارات نسل روشن با مجوز رسمی از وزارت فرهنگ و ارشاد اسلامی و در اختیار داشتن خط تولید کامل چاپ کتاب (از تبدیل دست نوشته‌های صاحب اثر تا تحویل کتابی مرغوب و با کیفیت) و تجربه چاپ و انتشار بیش از ۱۰۰۰ عنوان کتاب در زمینه‌های مختلف(علمی، دانشگاهی، شعر،رمان و…) افتخار دارد در خدمت اساتید و نویسندگان عزیزی که تمایل دارند آثار و تالیفات خود را به ثبت برسانند باشد",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8962),
                            Name = "انتشارات نسل روشن"
                        },
                        new
                        {
                            Id = 13L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8964),
                            Description = "تشارات سخن یکی از ناشران ایرانی است که در حوزه‌های تاریخ، علوم اجتماعی و علوم انسانی، فرهنگ و ادبیات فعالیت دارد.[۱]مدیریت این انتشارات بر عهدهٔ علی‌اصغر علمی است.[۲]تاکنون ۱۲ عنوان کتاب از انتشارات سخن به عنوان کتاب سال شناخته شده‌است.",
                            Establishment_Date = new DateTime(1990, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8965),
                            Name = "انتشارات سخن"
                        },
                        new
                        {
                            Id = 14L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8966),
                            Description = "ما انتشارات پرتقال هستیم، بچه‌ی انتشارات خیلی‌سبز!\r\n                    یه خواهشی داشتیم... لطفا بزرگ نشید !\r\n                    ما هم یه روز مثل شما و هم سن و سال شما بودیم؛ خوش‌حال بودیم و بی‌دلیل می‌خندیدیم!\r\n                    تا اینکه یکی صدامون کرد... چپ چپ به بستنی توی دستمون و توپی که تو دست دیگه‌مون بود نگاه کرد،\r\n                    مستقیم توی چشم‌هامون زل زد و گفت: «بهتره زودتر بزرگ بشید؛ بزرگ شدن و بزرگ بودن خیلی خوبه...»",
                            Establishment_Date = new DateTime(2016, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8967),
                            Name = "نشر پرتقال"
                        },
                        new
                        {
                            Id = 15L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8969),
                            Description = "",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8970),
                            Name = "انتشارات کتاب همراه"
                        },
                        new
                        {
                            Id = 16L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8971),
                            Description = "نشر کتاب کوله‌پشتی یک مؤسسه انتشاراتی کتاب در ایران است که از سال ۱۳۹۰ فعالیتش را آغاز و عمده فعالیتش در زمینه ادبیات داخلی و خارجی است.[۱] شهرت این انتشاراتی از آنجایی است که برای نخستین مرتبه در ایران، کتاب‌های منتشر شده را دارای گارانتی رسمی نموده‌است[۲] این انتشاراتی همچنین در زمینه چاپ و نشر رمان و داستان بلند نیز با انتشار آثاری در این زمینه، نامزد جایزه ادبی جلال آل‌احمد سال ۱۳۹۷ گردیده‌است.",
                            Establishment_Date = new DateTime(2011, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8972),
                            Name = "انتشارات کتاب کوله‌پشتی"
                        },
                        new
                        {
                            Id = 17L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8974),
                            Description = "انتشارات گیوا با چشم‌انداز بین‌المللی و با هدف اعتلای فرهنگ ایرانی از آبان ۱۳۹۴ کار خود را به عنوان ناشر مستقل در زمینه‌ی دانشگاهی آغاز کرد و یک‌سال بعد حوزه‌ی فعالیتش را در عرصه‌ی شعر و ادبیات و کتاب‌های عمومی نیز گستراند. گیوا با شعار «هر ایرانی یک کتاب»، با توکل به خدا و تکیه به اعتماد مردمان خوبمان تصمیم دارد در گام نخستِ چشم‌انداز ِ ایده‌آلیستی خود از هر ایرانی اهل قلم، کتابی به چاپ برساند و در گام دوم و به کمک آثار نویسندگان عزیز، موضوعات کتاب‌ها را تنوع‌بخشی کرده و با ورود بیشتر و بهتر به عرصه‌های شعر، ترانه، داستان، رمان، نقد و نظریه، فیلمنامه و نمایشنامه، منطق، فلسفه و روانشناسی، حقوق و علوم سیاسی، مدیریت و اقتصاد، تاریخ و هنر، علوم پایه و … ویترینی به وسعت ایران بزرگ و فراتر از آن تشکیل دهد تا هر نوع سلیقه‌‌ای را تامین نماید.",
                            Establishment_Date = new DateTime(2015, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8974),
                            Name = "انتشارات گیوا"
                        },
                        new
                        {
                            Id = 18L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8976),
                            Description = "انتشارات جامی ناشر برترین کتابهای ادبی، هنری و تاریخی است .این نشر در سال ۱۳۶۹ تاسیس شد.\r\n                    عمده فعالیت این نشر در زمینه ی ترجمه ی رمان های کلاسیک است. انتشارات مصدق و انتشارات فرهنگ برتر جزء موسسات انتشاراتی هستند که وابسته به نشر جامی فعالیت می کنند.\r\n                    آثاری نویسندگانی چون جورج اورول، امیلی برونته، هاینریش بل، مارک تواین، شارلوت بروتنه، جوجو مویز، ارنست همینگوی و جین آستین در این انتشارات چاپ شده است.",
                            Establishment_Date = new DateTime(1990, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8977),
                            Name = "انتشارات جامی"
                        },
                        new
                        {
                            Id = 19L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8978),
                            Description = "مختصری در مورد نیماژ بدانید:\r\n                    نیماژ؛ نشری‌ که فعالیت خود را سال 92 در زمينه‌ی شعر به‌صورت تخصصي آغاز کرده، جذابیت و امر چالش‌برانگیز شعر در سطوح مختلف جامعه را دلیلی بر انتخاب این حوزه برای آغاز فعالیت خود می‌داند. اما در سال 93 و ادامه‌ی آن این نشر با نگاهی متفاوت‌تر از شروع فعالیت خود،به انتشار عناوینی در زمینه‌ی ادبیات داستانی پرداخته، که در برگیرنده‌ی آثار نویسندگان ایرانی و خارجی‌ست در همین مسیر سرفصل‌هایی چون فلسفه و علوم اجتماعی را در سیاست‌های نشر کتاب خود تعریف کرد.",
                            Establishment_Date = new DateTime(2013, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8979),
                            Name = "نشر نیماژ"
                        },
                        new
                        {
                            Id = 20L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8981),
                            Description = "",
                            Establishment_Date = new DateTime(2009, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8982),
                            Name = "انتشارات آزرمیدخت"
                        },
                        new
                        {
                            Id = 21L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8983),
                            Description = "",
                            Establishment_Date = new DateTime(2017, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8984),
                            Name = "انتشارات ندای معاصر"
                        },
                        new
                        {
                            Id = 22L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8986),
                            Description = "مدیریت این انتشارات از سال 1357 تا پایان سال 1358 رئیس حسابداری انتشارات امیرکبیر بوده و از آن سال به بعد با چند نفر از دوستان شرکت نشر نو را تأسیس کرده و مدیریت آن را به عهده داشته است.\r\n                    در سال 1367 مدیریت انتشارات البرز را عهده ­دار بوده است و از سال 1375 تا امروز مدیر نشر پیکان است.\r\n                    تاکنون بیش از دو هزار عنوان کتاب به مدیریت ایشان منتشر شده است و اکنون این انتشارات در حوزه ­های روان­شناسی، فلسفه، ادبیات ایران، ادبیات جهان، هنر، علم، تاریخ، سیاست و … فعالیت دارد.",
                            Establishment_Date = new DateTime(1996, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8987),
                            Name = "نشر پیکان"
                        },
                        new
                        {
                            Id = 23L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8988),
                            Description = "",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8989),
                            Name = "انتشارات ذهن‌ آویز"
                        },
                        new
                        {
                            Id = 24L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8990),
                            Description = "نشر ترنگ در سال 1394 با هدف جذب مخاطبان در حوزه روان درمانگري و عرفان تاسيس شد. اين نشر تاکنون تمرکز اصلي خود را بر ارتقاء سطح کيفي زندگي ايرانيان متمرکز کرده است و با اتکا به شناخت خود از دغدغه هاي خانواده هاي ايراني سعي در چاپ کتب متنوع در زمينه بيداري، خودآگاهي و سلامت روان داشته است به مدد حمايت شما سروران گرامي اين نشر با قدرت به مسير خود ادامه مي دهد و با چاپ کتب مناسب از شناخته شده ترين مولفان، زمينه بهبود روند زندگي و سلامت رواني مخاطبان خود را مطالبه خواهد کرد.",
                            Establishment_Date = new DateTime(2015, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8991),
                            Name = "نشر ترنگ"
                        },
                        new
                        {
                            Id = 25L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8993),
                            Description = "",
                            Establishment_Date = new DateTime(2013, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8994),
                            Name = "انتشارات شهر پدرام"
                        },
                        new
                        {
                            Id = 26L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8995),
                            Description = "",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8996),
                            Name = "انتشارات زرین کلک"
                        },
                        new
                        {
                            Id = 27L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8998),
                            Description = "تنها یک سرک کوچک به سایت bidgolpublishing.com کافی‌ست که با نشر جذاب و خوش‌سلیقهٔ «بیدگل» آشنا شوید و تصمیم بگیرید توی عناوین کتاب‌های منتشرشده‌اش بچرخید. این انتشارات که توسط آقای «محمدحسن شاطریان بیدگلی» تاسیس شده، و احتمالاً اسم زیبایش را هم وامدار نام خانوداگی ایشان است، در زمینه‌های گوناگونی کتاب منتشر می‌کند که با یک مرور کلی روی عناوین آثار منتشرشده‌اش، می‌بینیم که اغلب این کتاب‌ها در حوزهٔ سینما، ادبیات، تئاتر، ادبیات داستانی، نگارش خلاق، دانش زندگی، هنرهای نمایشی و تاریخچهٔ آن‌ها، هنرهای تجسمی، دانش عمومی و مواردی از این دست به‌طور تخصصی، قرار می‌گیرند.",
                            Establishment_Date = new DateTime(2007, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(8999),
                            Name = "نشر بیدگل"
                        },
                        new
                        {
                            Id = 28L,
                            CreateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9000),
                            Description = "",
                            Establishment_Date = new DateTime(1978, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastUpdateDate = new DateTime(2023, 3, 25, 12, 5, 42, 152, DateTimeKind.Local).AddTicks(9001),
                            Name = "فناوری نوین"
                        });
                });

            modelBuilder.Entity("EShop.Domain.Entities.Access.UserRole", b =>
                {
                    b.HasOne("EShop.Domain.Entities.Access.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Domain.Entities.Account.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Book", b =>
                {
                    b.HasOne("EShop.Domain.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("EShop.Domain.Entities.BookCategory", b =>
                {
                    b.HasOne("EShop.Domain.Entities.Book", "Book")
                        .WithMany("CategoriesLink")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Domain.Entities.Category", "Category")
                        .WithMany("BooksLink")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Access.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Account.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Book", b =>
                {
                    b.Navigation("CategoriesLink");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Category", b =>
                {
                    b.Navigation("BooksLink");
                });

            modelBuilder.Entity("EShop.Domain.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
